name: my_freezer
description: "Мобільний додаток для керування продуктами у морозильній камері. Відстежуйте терміни зберігання, організовуйте продукти за категоріями та отримуйте сповіщення про терміни придатності."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  shared_preferences: ^2.2.2
  provider: ^6.1.1

  # State Management
  equatable: ^2.0.5

  # Navigation
  auto_route: ^7.8.4

  # Dependency Injection
  get_it: ^7.6.7

  # Local Storage
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  path: ^1.8.3

  # UI Components
  flutter_slidable: ^3.0.1
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0

  # Utils
  uuid: ^4.3.3
  logger: ^2.0.2+1

  # Freezed
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  analyzer: ^5.13.0
  
  # Code Generation
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2
  isar_generator: ^3.1.0+1

  # Freezed
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    
  # Fonts section removed as we're using Material Design's built-in Roboto font
